name: MLOPs fifa value predict Github Actions
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
        exclude:
          - os: windows-latest
            python-version: '3.6'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make install
    - name: Format code
      run: |
        make format
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    
        
